version: "3.9"
services:
  dummy-server:
    build:
      context: .
    links:
      - postgres
    ports:
      - "3000:3000"
    environment:
    - PGUSER=postgres
    - PGHOST=postgres
    - PGPASSWORD=mysecretpassword
    - PGDATABASE=foo
    - PGPORT=5432
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_DB=foo
    volumes:
      - ./fixtures:/docker-entrypoint-initdb.d/:ro
volumes:
  logvolume01: {}
