name: build
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout pack
        uses: actions/checkout@v2
        with:
          repository: stefan-hoeck/idris2-pack
          path: idris2-pack
          ref: 'main'
      - name: Cache Docker
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: build
        run: |
          docker build . -t snazzybucket/dummy-server
        shell: bash
